### ISSUE TITLE
lineage_mutations is broken for us on latest version

### ISSUE THREAD

**Issue by xguse** [outbreak-info/python-outbreak-info#47]
It works fine with single lineage names but returns a results object with zero results when a list is provided.

I tried to show you the version we are running in the code but it looks like you guys dont follow that particular convention, so its this commit: `aa5676d`

![image](https://github.com/outbreak-info/python-outbreak-info/assets/138931/afd008cb-5559-4645-99d8-cec76cf22cfd)

So those work and are present. But when I ask for both of them in a list I get this:

![image](https://github.com/outbreak-info/python-outbreak-info/assets/138931/c3448f0c-9f0d-4e2d-a649-121fda39c501)

Am I doing something wrong?

This is pretty frustrating since this was working fine a couple months ago. 

For now, I can write a for loop and jus ask for all of my lineages in a single API call, but I am pretty sure y'all would prefer me hitting your API once vs the 2000 I need.

**Comment by cmaceves** [comment]
Hi! Thanks for brining this up - you aren't doing anything wrong, we clearly have some bugs going on on the backend. Someone from our team will look into this when we can!

**Comment by xguse** [comment]
So you think its server-side then? I suppose that would make sense. Thanks for checking it out.

**Comment by mindoftea** [comment]
@xguse Thank you for writing in. We deployed a new, more efficient version of our API recently which included some behavior changes like this one. We recommend installing this commit of the outbreak python package from github for the best compatibility: `pip install git+https://github.com/outbreak-info/python-outbreak-info.git@d4a21203c27ecef41e3d6d97213133271af99e77`. Documentation updates around these changes will be completed soon.

Previously, queries to lineage-mutations with multiple lineages were handled with an internal for loop, so that is an acceptable approach; please put a ~75ms sleep in the loop to reduce our peak loading so other users are less affected. At some point we may reimplement this feature using a more efficient strategy -- we'll let you know if we do.

**Comment by xguse** [comment]
@mindoftea Thanks for that explanation.

Did I interpret you correctly in the following summary:

1. updates were made to the backend before the frontend could catch up
2. that commit you suggested is the most synced up with the back-end, but its changes are undocumented
3. me doing a for loop is an acceptable work-around for now but to be nice to everyone I should sleep for 0.075 s each loop if I take this route

If I am correct there, I have now added this sleep.

Aside from me in development phase, I should only run this once a month on average, but I will still be doing the sleeping.

I will update the package itself once you make the release.

Thank you for everything.
